name: 'analysis'
version: '1.0.0'

profile: 'analysis'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

vars:
  data_path: "{{ env_var('DBT_DATA_PATH', '../../../data') }}"

models:
  analysis:
    +materialized: external
    staging:
      +schema: staging
    intermediate:
      +schema: intermediate
    marts:
      +schema: marts


