analysis:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: "{{ env_var('DBT_DUCKDB_PATH', '/home/bdn/coingecko-assessment/data/analysis.duckdb') }}"
      threads: 4
      schema: main

